import { ChatMessageDTO, ConversationPreview } from "../interfaces/interface";

export const conversations: ConversationPreview[] = [
  {
    id: "conversation-meera",
    name: "Meera",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBwmspsd8HcYdGJgqW7JD1rtIDa-jHzBBn7xp3azC-9Rohrm0ZCeIW9ZqWq6pqC4YiWK_UjK2kXhtgSy9cWFXBxK5D9A4d7FfwcjR6z7HufFVwxLBC9fm2tyFiuYQ49KD3ZL-QdQIhzKvERrSak2VpSJ55TDRrIu-q1Ee8ujnRnWhU0qJHH-Gj9XAsoD0zgYN0U7OuxdXMWdQgZKVRpCeeZ7UJpCgjFpjz3BAOqmEIAVHjxjKFF2TTX5YLdwcHSeL7TaCr8Nt1WKHk",
    preview: "That itinerary looks perfect!",
    lastMessageLabel: "10:24 AM",
    online: true,
    unread: true,
  },
  {
    id: "conversation-javier",
    name: "Javier",
    avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDevJ3uMuQT0dj1I2xev4kJ5hSlj_dQ2qjTdRh-OE0Y0PkhFOcxT10DibngGzrtO2kifAxgvRDd75wtrgP7eeYZtX1AoBrIcs3rtH1agXVqvnRHP4dAa73EIpE3gsQMmTAVEK2zabUiIaKzHcppuuv6Ar3MC1-6TqRH2jtoqMHW4hhCcqk0Xhj-CX_IjMxcXC1fefpcf7xTef2XSdWkqqlsud5ktC-Tms_6_bAGNSP2AuSReRi3gc93is33DNqehFBxd8qo3DqjNUQ",
    preview: "Sent a location",
    lastMessageLabel: "Yesterday",
    pinned: true,
  },
  {
    id: "conversation-liam",
    name: "Liam",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop",
    preview: "See you at the airport!",
    lastMessageLabel: "9:45 AM",
    online: true,
  },
  {
    id: "conversation-sophia",
    name: "Sophia",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop",
    preview: "Did you check the weather?",
    lastMessageLabel: "8:30 AM",
  },
  {
    id: "conversation-noah",
    name: "Noah",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop",
    preview: "Booking the hotel now.",
    lastMessageLabel: "Yesterday",
  },
  {
    id: "conversation-emma",
    name: "Emma",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop",
    preview: "Can't wait for Bali!",
    lastMessageLabel: "Yesterday",
  },
  {
    id: "conversation-oliver",
    name: "Oliver",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop",
    preview: "Found a great surf spot.",
    lastMessageLabel: "Monday",
  },
  {
    id: "conversation-ava",
    name: "Ava",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop",
    preview: "Is the visa ready?",
    lastMessageLabel: "Monday",
  },
  {
    id: "conversation-james",
    name: "James",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop",
    preview: "Let's grab dinner tonight.",
    lastMessageLabel: "Sunday",
  },
  {
    id: "conversation-isabella",
    name: "Isabella",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&h=100&fit=crop",
    preview: "Sent you the packing list.",
    lastMessageLabel: "Sunday",
  },
];

export const initialMessages: ChatMessageDTO[] = [
  {
    id: "message-1",
    conversationId: "conversation-meera",
    senderId: "meera-user-id",
    content: "Hey! I've been looking at some spots in Ubud. What do you think about this place for our first day?",
    createdAt: new Date("2026-08-13T10:18:00"),
    updatedAt: new Date("2026-08-13T10:18:00"),
  },
  {
    id: "message-2",
    conversationId: "conversation-meera",
    senderId: "current-user-id",
    content: "Oh wow, that looks absolutely stunning! Definitely adding that to the list. I've used the AI planner to suggest a morning flow for us. Check this out:",
    createdAt: new Date("2026-08-13T10:22:00"),
    updatedAt: new Date("2026-08-13T10:22:00"),
  },
  {
    id: "message-3",
    conversationId: "conversation-meera",
    senderId: "meera-user-id",
    content: "That itinerary looks perfect! The breakfast spot has amazing reviews. I'm so excited! 🌴",
    createdAt: new Date("2026-08-13T10:24:00"),
    updatedAt: new Date("2026-08-13T10:24:00"),
  },
  {
    id: "message-4",
    conversationId: "conversation-meera",
    senderId: "current-user-id",
    content: "I've checked the flight times, we land at 3 PM. Should we book a Grab or a private driver?",
    createdAt: new Date("2026-08-13T10:26:00"),
    updatedAt: new Date("2026-08-13T10:26:00"),
  },
  {
    id: "message-5",
    conversationId: "conversation-meera",
    senderId: "meera-user-id",
    content: "A private driver might be easier with all our luggage. I know a reliable one!",
    createdAt: new Date("2026-08-13T10:28:00"),
    updatedAt: new Date("2026-08-13T10:28:00"),
  },
  {
    id: "message-6",
    conversationId: "conversation-meera",
    senderId: "current-user-id",
    content: "Perfect. Also, did you exchange currency yet? Or should we just use ATMs there?",
    createdAt: new Date("2026-08-13T10:30:00"),
    updatedAt: new Date("2026-08-13T10:30:00"),
  },
  {
    id: "message-7",
    conversationId: "conversation-meera",
    senderId: "meera-user-id",
    content: "ATMs are usually fine, but I'll bring some USD just in case.",
    createdAt: new Date("2026-08-13T10:32:00"),
    updatedAt: new Date("2026-08-13T10:32:00"),
  },
  {
    id: "message-8",
    conversationId: "conversation-meera",
    senderId: "current-user-id",
    content: "Good call. For Ubud, I really want to try 'Locavore'. Have you heard of it?",
    createdAt: new Date("2026-08-13T10:35:00"),
    updatedAt: new Date("2026-08-13T10:35:00"),
  },
  {
    id: "message-9",
    conversationId: "conversation-meera",
    senderId: "meera-user-id",
    content: "Yes! It's supposed to be incredible. We should definitely book a table in advance.",
    createdAt: new Date("2026-08-13T10:38:00"),
    updatedAt: new Date("2026-08-13T10:38:00"),
  },
  {
    id: "message-10",
    conversationId: "conversation-meera",
    senderId: "current-user-id",
    content: "I'll handle the reservation. What about the packing list? Sunscreen and bug spray are top of my list.",
    createdAt: new Date("2026-08-13T10:40:00"),
    updatedAt: new Date("2026-08-13T10:40:00"),
  },
  {
    id: "message-11",
    conversationId: "conversation-meera",
    senderId: "meera-user-id",
    content: "Definitely! And a light raincoat, it's the tropical season after all.",
    createdAt: new Date("2026-08-13T10:42:00"),
    updatedAt: new Date("2026-08-13T10:42:00"),
  },
];
